service: exchange-cr-alexa-skill

plugins:
  - serverless-webpack
  - serverless-alexa-skills

provider:
  name: aws
  runtime: nodejs8.10

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  config: ${file(./config/serverless/dev.yml)}
  alexa:
    vendorId: ${self:custom.config.AMAZON_VENDOR_ID}
    clientId: ${self:custom.config.AMAZON_CLIENT_ID}
    clientSecret: ${self:custom.config.AMAZON_CLIENT_SECRET}
    localServerPort: 9000
    skills:
      - id: ${self:custom.config.AMAZON_SKILL_ID}
        manifest: ${file(./config/alexa/skill.yml)}
        models:
          en-US: ${file(./config/alexa/models/en-US.json)}

package:
  individually: true

functions:
  getExchange:
    handler: src/handler.startExchange
    events:
      - alexaSkill: ${self:custom.config.AMAZON_SKILL_ID}
